language: python
python:
  - "3.5"
# command to install dependencies
install:
    - pip install -r requirements.txt   
services:
  - mysql
  
env: # => 4
      -DJANGO=1.10 DB=mysql

before_script: # => 6
      - mysql -e 'create database sampleDB;' -u root
      - python manage.py syncdb --noinput
script: # => 7
      - py.test runTests.py
      - python manage.py test

